@hapiApi = http://localhost:8080/fhir
@id = 1
### CREATE Practitioner
POST {{hapiApi}}/Patient
Content-Type: application/json

{
  "resourceType": "Patient",
   "id": "3",
  "gender": "male",
  "birthDate": "1980-01-01",
  "name": [
    {
      "family": "sahani",
      "given": [
        "Anita"
      ]
    }
  ]
}

### READ Practitioner by ID (replace {id} with actual ID)
GET {{hapiApi}}/Practitioner/{{id}}

### SEARCH Practitioner by family name
GET {{hapiApi}}/Practitioner?family=sahani

### UPDATE Practitioner (replace {id} with actual ID)
PUT {{hapiApi}}/Practitioner/{id}
Content-Type: application/json

{
    "resourceType": "Practitioner",
    "name": [
        {
            "family": "Smith",
            "given": ["Alice", "Marie"]
        }
    ],
    "gender": "female",
    "qualification": [
        {
            "code": {
                "text": "Specialist"
            }
        }
    ]
}

### DELETE Practitioner (replace {id} with actual ID)
DELETE{{hapiApi}}/Practitioner/{id}
